In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('iris.csv')

In [15]:
data = np.array(df.ix[:,1:5])

In [17]:
label = np.array(df.ix[:,5])

In [18]:
data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [19]:
label[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [20]:
train_x,test_x,train_y,test_y = train_test_split(data,label,test_size=0.3)

In [21]:
train_x[:5]

array([[ 5.1,  3.8,  1.6,  0.2],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 4.8,  3.4,  1.9,  0.2]])

In [22]:
test_x[:5]

array([[ 5.1,  3.8,  1.9,  0.4],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 5.6,  3. ,  4.5,  1.5]])

In [24]:
train_y[:5]

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa'], dtype=object)

In [25]:
test_y[:5]

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler()

In [29]:
sc.fix(train_x)

AttributeError: 'StandardScaler' object has no attribute 'fix'